### ISSUE TITLE
How to get the simplified expression?

### ISSUE THREAD

**Issue by chaosink** [aekul/aether#4]
```
aether::variable<0> u0;
aether::variable<1> u1;
auto r = sqrt(aether::one - sq(u0));
auto phi = two * get_pi() * u1;
auto x = r * cos(phi);
auto x_jac = aether::jacobian(x);
auto x_det = abs(rcp(make_expr(determinant_tag, x_jac)));
```
How to simplify `x_det` which should be `0`?

- - -

```
aether::variable<0> u0;
aether::variable<1> u1;
auto r = sqrt(aether::one - sq(u0));
auto phi = two * get_pi() * u1;
auto x = r * cos(phi);
auto y = r * sin(phi);
auto z = u0;
auto dir = make_vector_expr(x, y, z);
auto dir_jac = aether::jacobian(dir);
auto dir_det = abs(rcp(make_expr(determinant_tag, dir_jac)));
```
How to simplify `dir_det` which should be `1/(2pi)` ?

**Comment by aekul** [comment]
https://github.com/aekul/aether/commit/2e89cf4616add3c978965f907f8acf467b6e228e should fix the first example. Calling `det(x)` should now return `0`. For the second example, calling `det(dir)` should give `1/(2pi)`.

As mentioned in https://github.com/aekul/aether/issues/3, `make_expr()` is not intended to be called directly. It can potentially skip some simplification steps. Using `det()` will ensure that simplification occurs. In general, Aether will automatically attempt to simplify all expressions (unless created with `make_expr()`). If you see something that's not simplified, you may have found a bug, so feel free to create another issue.

**Comment by chaosink** [comment]
Actually the situation where I have to call `make_expr()` is because I can't call `det()` to get a simplified expression. 

And, thanks for your work and the code.
C++ template metaprogramming is amazing!
And Aether is what motivates me to begin to learn it.

**Comment by aekul** [comment]
Glad you're finding Aether interesting!
